Fixed some more code injection issues (#912)

diff --git a/.github/actions/security/bandit/action.yml b/.github/actions/security/bandit/action.yml
--- a/.github/actions/security/bandit/action.yml
+++ b/.github/actions/security/bandit/action.yml
@@ -180,15 +180,18 @@ runs:
     - name: Upload reports
       env:
         suffix: ${{inputs.report_suffix}}
+        REPORT_PATH: ${{ steps.run-bandit.outputs.report_path }}
       if: steps.run-bandit.outputs.report_path != ''   # if any report is available
       uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f  # v7.0.0
       with:
         name: bandit-results-${{ steps.run-bandit.outputs.rand_suffix }}${{ env.suffix }}
-        path: ${{ steps.run-bandit.outputs.report_path }}
+        path: "${REPORT_PATH}"
         retention-days: 7
 
     - name: Fix SARIF severity levels
       if: contains(steps.run-bandit.outputs.report_path, '.sarif')
+      env:
+        REPORT_PATH: ${{ steps.run-bandit.outputs.report_path }}
       shell: bash
       run: |
         jq '
@@ -201,8 +204,8 @@ runs:
               end
             )
           )
-        ' "${{ steps.run-bandit.outputs.report_path }}" > fixed-report.sarif
-        mv fixed-report.sarif "${{ steps.run-bandit.outputs.report_path }}"
+        ' "${REPORT_PATH}" > fixed-report.sarif
+        mv fixed-report.sarif "${REPORT_PATH}"
 
     - name: Upload sarif
       if: inputs.upload-sarif == 'true' && contains(steps.run-bandit.outputs.report_path, '.sarif')
@@ -212,7 +215,9 @@ runs:
 
     - name: Fail if Bandit found issues
       if: inputs.fail-on-findings == 'true' && steps.run-bandit.outputs.exit_code != '0'
+      env:
+        EXIT_CODE: ${{ steps.run-bandit.outputs.exit_code }}
       shell: bash
       run: |
-        echo "Bandit found issues. Failing the job with exit code ${{ steps.run-bandit.outputs.exit_code }}"
-        exit ${{ steps.run-bandit.outputs.exit_code }}
+        echo "Bandit found issues. Failing the job with exit code ${EXIT_CODE}"
+        exit "${EXIT_CODE}"
