feat: sign docker container with cosign (#6)
* feat: add cosign for docker images

diff --git a/.github/workflows/post-merge.yml b/.github/workflows/post-merge.yml
--- a/.github/workflows/post-merge.yml
+++ b/.github/workflows/post-merge.yml
@@ -109,11 +109,16 @@ on:  # yamllint disable-line rule:truthy
         required: false
         default: false
         type: boolean
+      runs_on:
+        description: "Label for runner"
+        required: false
+        default: "ubuntu-latest"
+        type: string
 permissions:
   contents: write
 jobs:
   run-repo-pipelines:
-    runs-on: ubuntu-latest
+    runs-on: ${{ inputs.runs_on }}
     env:
       GIT_SHORT_URL: ${{ github.repository }}
       PROJECT_NAME: ${{ github.repository }}
@@ -271,6 +276,31 @@ jobs:
         working-directory: ${{ inputs.project_folder }}
         run: |
           make docker-push
+
+      - name: Install cosign
+        if: ${{ inputs.run_docker_push }}
+        uses: ./ci/.github/actions/bootstrap
+        with:
+          gh_token: ${{ secrets.SYS_ORCH_GITHUB }}
+          bootstrap_tools: "cosign"
+
+      - name: Sign Docker images
+        if: ${{ inputs.run_docker_push }}
+        env:
+          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
+          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
+        run: |
+          images=$(docker images --digests --format "{{.Repository}}@{{.Digest}}" | grep '^080137407410.dkr.ecr.us-west-2.amazonaws.com')
+          images_json=$(echo "$images" | jq -R . | jq -s -c .)
+          for image in $(echo "$images_json" | jq -r '.[]'); do
+            echo "Signing $image"
+            # Check if the image is not empty
+            if [ -n "$image" ]; then
+              cosign sign -y --key env://COSIGN_PRIVATE_KEY "$image" || echo "Failed to sign $image"
+            else
+              echo "No images found to sign."
+            fi
+          done
 
       - name: Build Helm chart
         if: ${{ inputs.run_helm_build }}
