feat: enable binaries sign

diff --git a/.github/workflows/post-merge.yml b/.github/workflows/post-merge.yml
--- a/.github/workflows/post-merge.yml
+++ b/.github/workflows/post-merge.yml
@@ -220,6 +220,13 @@ jobs:
             ${{ env.REPO_PROJECT }}-${{ runner.os }}-go-${{ env.GOLANG_VER }}-
             ${{ env.REPO_PROJECT }}-${{ runner.os }}-go-
 
+      - name: Install cosign
+        if: ${{ inputs.run_docker_push }}
+        uses: ./ci/.github/actions/bootstrap
+        with:
+          gh_token: ${{ secrets.SYS_ORCH_GITHUB }}
+          bootstrap_tools: "cosign"
+
       - name: Build Code
         if: ${{ inputs.run_build }}
         working-directory: ${{ inputs.project_folder }}
@@ -227,6 +234,19 @@ jobs:
         run: |
           echo "Building the code"
           make build
+
+      - name: Find and Sign Binaries
+        env:
+          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
+          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
+        run: |
+          # Find executable
+          binaries=$(find ${{ inputs.project_folder }} -type f -executable)
+      
+          for binary in $binaries; do
+            echo "Signing $binary"
+            cosign sign-blob --key env://COSIGN_PRIVATE_KEY "$binary" || echo "Failed to sign $binary"
+          done
 
       - name: Lint Code
         if: ${{ inputs.run_lint }}
@@ -276,13 +296,6 @@ jobs:
         working-directory: ${{ inputs.project_folder }}
         run: |
           make docker-push
-
-      - name: Install cosign
-        if: ${{ inputs.run_docker_push }}
-        uses: ./ci/.github/actions/bootstrap
-        with:
-          gh_token: ${{ secrets.SYS_ORCH_GITHUB }}
-          bootstrap_tools: "cosign"
 
       - name: Sign Docker images
         if: ${{ inputs.run_docker_push }}
